### ISSUE TITLE
[BUG] AttributeError: module 'keras.backend' has no attribute 'is_tensor'

### ISSUE THREAD

**Issue by hadaev8** [arogozhnikov/einops#134]
**Describe the bug**
Rearrange doesnt work then huggingfcae imported first

**Reproduction steps**
https://colab.research.google.com/drive/14b3R330bt658rjpZr7HXQb7CHXClgWcy?usp=sharing

**Expected behavior**
Not bugging.

**Your platform**
Google colab

**Comment by hellohawaii** [comment]
Yes, I met the same problem.
in _backends.py, https://github.com/arogozhnikov/einops/blob/fdfb9da59dd9552f3d69e3bfe87b4f400fa2b383/einops/_backends.py#L514

**Comment by hellohawaii** [comment]
How about upgrading to the newest version by 
pip install --upgrade --force-reinstall git+https://github.com/arogozhnikov/einops.git

I met the same problem and solved it but upgrading the codes.before upgrading, I found the _backends.py has the following codes, which is different from the repo.

```
class KerasBackend(AbstractBackend):
    framework_name = 'keras'

    def __init__(self):
        import keras
        self.keras = keras
        self.K = keras.backend

    def is_appropriate_type(self, tensor):
        return self.K.is_tensor(tensor) and self.K.is_keras_tensor(tensor)
```

After upgrading, it becomes: 


```
class KerasBackend(AbstractBackend):
    framework_name = 'keras'

    def __init__(self):
        import tensorflow as tf
        self.tf = tf
        self.keras = tf.keras
        self.K = tf.keras.backend

    def is_appropriate_type(self, tensor):
        return self.tf.is_tensor(tensor) and self.K.is_keras_tensor(tensor)
```


Notice that keras.is_tensor() is replaced by tf.is_tensor().

**Comment by arogozhnikov** [comment]
Hi @hadaev8, thanks for reproducible example.
Solution is as @hellohawaii recommends - install einops from master. I'll push a release to fix that soon

Another, more reasonable solution IMO is to **remove keras**. 

Independent keras package is practically dead, and instead of dropping that one completely, tensorflow [imports it](https://github.com/tensorflow/tensorflow/blob/3d93ce9633b8c7015d5e9067af76ed4061dc6caf/tensorflow/tools/docs/base_dir.py#L30) 😱 (huggingface seems to make this mistake). 

Huggingface still imports tf no matter if you use that or not, and tf imports keras.

**Comment by jimtalksdata** [comment]
This solved my issue, thanks.

**Comment by hadaev8** [comment]
Installing from git helps, thanks.
