### ISSUE TITLE
reduce does not support tensors as axes length argument

### ISSUE THREAD

**Issue by olgafour1** [arogozhnikov/einops#184]
This is a naive way to reproduce the issue!

pool_tensor=tf.random.normal([1,8,256,512], 0, 1, tf.float32, seed=1)

l = tf.math.ceil(n / m)
einops_eq = '... (n l) d -> ... n d'
tf_tensor = reduce(pool_tensor, einops_eq, 'sum', l = l)

**Comment by arogozhnikov** [comment]
Hi @olgafour1 ,

it's hard to see what was intention of the reduce operation, as some variables (n, m) are missing, so I'll try to guess

```python
pool_tensor=tf.random.normal([1,8,256,512], 0, 1, tf.float32, seed=1)

l = tf.math.ceil(n / m)
tf_tensor = reduce(pool_tensor, '... (n l) d -> ... n d', 'sum', l = l)
```

One remark is that tf.ceil returns float tensor, so it can't be used as an axis length, as axis size should be integer.

It looks like you wanted to split n-dimension into chunks of length m. If so, this will be an equivalent to:

```python
m = 2
l = pool_tensor.shape[-2] // m
tf_tensor = reduce(pool_tensor, '... (n l) d -> ... n d', 'sum', l = l)
```
You'll see that it works, because this code does not use tensor variables.

Previous can be simplified even more.

```python
m = 2
tf_tensor = reduce(pool_tensor, '... (m l) d -> ... m d', 'sum', m=m)
```

I had to make several assumptions about the code intentions just to demonstrate that for shape manipulations one usually does not need variables.

`tf.Tensor`s pose a challenge of being immutable and unhashable at the same time. This conflicts with hashing which otherwise works very well. There are dirty hacks to make it working, but I'd better avoid them whenever possible. 
If for some reason you *have* to use tensors, I'd better collect some detailed code examples when this is required.

**Comment by arogozhnikov** [comment]
Closing. Still feel free to add details
