### ISSUE TITLE
einops tutorial on youtube

### ISSUE THREAD

**Issue by ksachdeva** [arogozhnikov/einops#228]
Hi,

The API design, documentation, and examples in this repository are so good that they do not need any other tutorial.

But to make others aware of the existence of this fantastic work I have created a tutorial on it.
https://www.youtube.com/watch?v=xGy75Pjsqzo

I have only talked about the rearrange API and maybe later would cover other goodies from this package.

Many thanks for this great work

Regards
Kapil

**Comment by arogozhnikov** [comment]
Hi Kapil, 

Einops certainly lacks the coverage on youtube, so that's very helpful.
Also it helps getting people aboard earlier when they start learning numpy/torch/tf. 

Currently it's more like we try to change bad habits that people already have, and a much better way would be to teach better practices earlier before they get muscle memory for reshapes :)

Will add links to your video in the documentation and description.

**Comment by arogozhnikov** [comment]
I've put a link in readme and in the community page of einops.rocks. 
Thanks once again for this nice video-introduction!
